# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fileservice.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/fileservice.proto\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x14\x46indSuccessorRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"=\n\x15\x46indSuccessorResponse\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x03\x32\xa5\x01\n\x0b\x46ileService\x12)\n\nUploadFile\x12\x0c.FileRequest\x1a\r.FileResponse\x12+\n\x0c\x44ownloadFile\x12\x0c.FileRequest\x1a\r.FileResponse\x12>\n\rFindSuccessor\x12\x15.FindSuccessorRequest\x1a\x16.FindSuccessorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.fileservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=27
  _globals['_FILEREQUEST']._serialized_end=58
  _globals['_FILERESPONSE']._serialized_start=60
  _globals['_FILERESPONSE']._serialized_end=91
  _globals['_FINDSUCCESSORREQUEST']._serialized_start=93
  _globals['_FINDSUCCESSORREQUEST']._serialized_end=127
  _globals['_FINDSUCCESSORRESPONSE']._serialized_start=129
  _globals['_FINDSUCCESSORRESPONSE']._serialized_end=190
  _globals['_FILESERVICE']._serialized_start=193
  _globals['_FILESERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
