# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileservice.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ileservice.proto\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2e\n\x0b\x46ileService\x12)\n\nUploadFile\x12\x0c.FileRequest\x1a\r.FileResponse\x12+\n\x0c\x44ownloadFile\x12\x0c.FileRequest\x1a\r.FileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fileservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=21
  _globals['_FILEREQUEST']._serialized_end=52
  _globals['_FILERESPONSE']._serialized_start=54
  _globals['_FILERESPONSE']._serialized_end=85
  _globals['_FILESERVICE']._serialized_start=87
  _globals['_FILESERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
